# Copyright 2021 Canonical
# See LICENSE file for licensing details.

options:

  ### Application-related options:
  server-ui-path:
    type: string
    default: /studio
    description: |
      The root path (exluding protocol, host, or port declaration) under
      which the Studio UI should be server.

  server-logging-level:
    type: string
    default: INFO
    description: |
      String identifier of the log level to be used for all library classes.
      Must be one of INFO, WARN, DEBUG, or TRACE, or OFF.

  server-pac4j-logging-level:
    type: string
    default: DEBUG
    description: |
      String identifier of the log level to be used by authentication-related
      PAC4J actions. Must be one of INFO, WARN, DEBUG, or TRACE, or OFF.

  ### Nginx Ingress Integrator-related options:
  enable-tls:
    type: boolean
    default: false
    description: |
      Boolean representing whether or not this Legend Application endpoint is
      accessed through HTTPS. Setting this option will not enable TLS on the
      service itself, and it is meant to be used in conjunction with the
      tls-secret-name config option on the Nginx Ingress Integrator Charm.
      Setting this option will cause the Gitlab Callback URLs to be prefixed
      by HTTPS instead of HTTP.

  external-hostname:
    type: string
    default: ""
    description: |
      String representing the DNS name this Application should respond to.
      By default, this will be the Application's name.
